name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci && npm run patch
      - run: npm run build
      - run: npm test
      - run: npm run docs
      - name: Deploy documentation
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: docs/
          remote_path: documentation/read-gedcom
          remote_host: docs.arbre.app
          remote_user: github
          remote_key: ${{ secrets.DEPLOY_KEY }}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci && npm run patch
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
